name = input("whats your name: ")
print("thats a stupid name " +name )                                                                                                                                    #this  game ulternates with input and print making it alternate beqeen you and the computor
input("Want to play a game ")
print("you will play anyways \nyou really thaugt you had a choise")
print("U play this game")
input("How much ")
print("would a")
input("wood ")
print("if a")
input("wood chuck ")
print("chuck wood")
input("How much wood would a wood chuck chuck if a wood chuck could chuck wood? ")
print("Haha you where wrong it was 7 \nyou are soo dum")
print("as they say " +name)
print("Dum Dum give me gum gum")
print("I WANT MY GUM")
input("will you give me my gum "+name )
print("you thaugt you had a choise again Omegalul")
print("you will get me gum anyways")
